---
# Usage: http://ruhoh.com/usage/configure/ 

RuhohSpec: '1.0'
theme : twitter
production_url : http://iwood.co.nr

posts:
  permalink: /blog/:year/:month/:day/:filename/
  summary_lines: 5
  latest: 10

pages:
  permalink: 'pretty'

paginator:
  namespace: "/posts/"
  per_page: 10
  root_page: "/"
  layout: "paginator"